# Generated by Django 4.2.16 on 2024-12-14 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_nflteamstats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NFLTeamStats',
        ),
    ]
