# Generated by Django 4.2.16 on 2024-12-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_nflplayerstats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nflplayerstats',
            name='offense_snaps',
        ),
        migrations.RemoveField(
            model_name='nflplayerstats',
            name='team_snaps',
        ),
        migrations.RemoveField(
            model_name='nflplayerstats',
            name='team_yards',
        ),
        migrations.RemoveField(
            model_name='nflplayerstats',
            name='yards_pct',
        ),
        migrations.AddField(
            model_name='nflplayerstats',
            name='adot',
            field=models.FloatField(default=0.0),
        ),
    ]
